# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e9e6eb65bcb8999a35f62fc6df142cbab25723eecf624016ec645b246ef4a25e8ea9010d2dab7f164d2414289af7ff37f03e3279679be0e92938bd50bcf9feb

test:
  secret_key_base: 4e17e3cc820ea98481f45ed09e2675ab5427ffa501f3ee0f880f20c1c778ad476d1fb576821a703fc3b9f7a60f926e04d8ecf29bd5faf9faef1bc3a19d61a828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
